GET http://localhost:8080/api/companies/

###
POST http://localhost:8080/api/companies/
Content-Type: application/json

{
  "name":"Dell"
}

###

GET http://localhost:8080/api/games/64e203ab5525cbdcc4a7966c


###
GET http://localhost:8080/api/kittens/64e203ab5525cbdcc4a7966c
###
DELETE http://localhost:8080/api/kittens/64e203ab5525cbdcc4a7966c/hj
###
DELETE http://localhost:8080/api/kittens/64e203ab5525cbdcc4a7966c/64e323827b6a34d15a9ec64b


###
POST http://localhost:8080/api/kittens/64e203ab5525cbdcc4a7966c HTTP/1.1
Content-Type: application/json

{
  "name":"Cica",
  "weight":12
}



###
GET http://localhost:8080/api/brands


###
GET http://localhost:8080/api/brands/64df4d800c74cbb1b6edd4af

###
DELETE http://localhost:8080/api/brands/

###
PATCH  http://localhost:8080/api/brands/64df4d800c74cbb1b6edd4b0
Content-Type: application/json

{
  "name":"HP"
}


###
GET http://localhost:8080/api/equipments?sortBy=amount&sortDirection=1&page=2&count=10


###
GET http://localhost:8080/api/equipments?page=0&count=10

###
GET http://localhost:8080/api/equipments/

###
Get http://localhost:8080/api/equipments/64d8826e8d91a88f4485f172
Content-Type:  application/json
###
PATCH http://localhost:8080/api/equipments/64d8826e8d91a88f4485f172
Content-Type:  application/json

{
  "name": "Beka",
  "type": "Power Managment",
  "amount": "1"
}

###

GET http://localhost:8080/api/employees/top-paid
###

GET http://localhost:8080/api/employees/

###
POST http://localhost:8080/api/employees/
Content-Type: application/json

{
  "name": "Valaki",
  "level": "Godlike",
  "position": "Joker"
}

###
DELETE http://localhost:8080/api/employees/64df7f564a519b34cf2b0291

###
PATCH http://localhost:8080/api/employees/63fc6e4bca1cb463caa21779
Content-Type:  application/json

{
  "name": "asd"
}
