GET http://localhost:8080/api/equipments?page=0&count=10

###
GET http://localhost:8080/api/equipments/

###
Get http://localhost:8080/api/equipments/64d8826e8d91a88f4485f172
Content-Type:  application/json
###
PATCH http://localhost:8080/api/equipments/64d8826e8d91a88f4485f172
Content-Type:  application/json

{
  "name": "Beka",
  "type": "Power Managment",
  "amount": "1"
}

###

GET http://localhost:8080/api/employees/

###
POST http://localhost:8080/api/employees/
Content-Type: application/json

{
  "name": "Valaki",
  "level": "Godlike",
  "position": "Joker"
}

###
DELETE http://localhost:8080/api/employees/63fc6e4bca1cb463caa21779

###
PATCH http://localhost:8080/api/employees/63fc6e4bca1cb463caa21779
Content-Type:  application/json

{
  "name": "asd"
}
